name: Tag version, build and release

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

jobs:
  delete-draft-release:
      name: Delete draft releases
      # electron-build often returns "socket hang up" error if it already been 
      # running and tries to override already existing files in the Google (draft) release

      runs-on: ubuntu-latest
      steps:
        - name: Delete draft releases
          uses: hugo19941994/delete-draft-releases@v0.1.0
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [ubuntu-latest]
        os: [ubuntu-latest, windows-latest, macos-latest]
      max-parallel: 1

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install snapcraft (Linux)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo snap install snapcraft --classic  
        
      - name: Install all dependencies
        run: |
          npm install

      - name: Build and publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run release
