name: Check if remembered to update version

on:
  pull_request:
    branches: [ master ]

jobs:
  check_if_version_changed:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Check if version updated
        run: | 
          # In case only a shallow clone was done
          git fetch --tags
          
          PACKAGE_VERSION=$(cat 'package.json' | jq -r '.version')      # E.g.  0.1.1
          LATEST_TAG=$(git tag -l --sort -version:refname | head -n 1)  # E.g. v0.1.1

          if [[ "${PACKAGE_VERSION}" && ! $(git tag | grep "${PACKAGE_VERSION}") ]]; then
            echo "Version has changed!"
            echo "Latest version tag is $LATEST_TAG while package.json has been updated to v${PACKAGE_VERSION}"
            exit 0  # Success
          else
            echo "The version number in package.json is not updated!"
            echo "The version number in package.json (v${PACKAGE_VERSION}) is <= the latest version tag ($LATEST_TAG)"
            exit 1  # Error
          fi
